# Permalinks
permalink:           pretty

# Setup
title:               Vibhanshu
tagline:             From a peasant to a prince to a... ;)
url:                 https://www.vibhanshu.io
#paginate:            1
baseurl:             ""
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Vibhanshu Bhardwaj
  url:               https://www.facebook.com/mcvib
  email:             bhardwajvibhanshu@gmail.com

# Custom vars
version:             0.0.1
github:
  repo:  

pages_list:       
  Meditations: '/meditations/'
# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
